# Generated by Django 5.2 on 2025-05-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='author',
            new_name='user',
        ),
    ]
