# Generated by Django 5.2 on 2025-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='title',
        ),
        migrations.AddField(
            model_name='setting',
            name='contain_lower_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='contain_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='contain_special_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='contain_upper_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='minimum_characters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
