# Generated by Django 5.2 on 2025-05-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_setting_content_remove_setting_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='user_id',
            new_name='user',
        ),
    ]
