# Generated by Django 5.2 on 2025-04-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='failed_attempt',
            new_name='failed_attempts',
        ),
    ]
