# Generated by Django 5.2 on 2025-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='digits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
