# Generated by Django 5.2 on 2025-04-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='author',
            new_name='user',
        ),
    ]
