# Generated by Django 5.2 on 2025-04-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_userdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='author',
            new_name='role',
        ),
    ]
