# Generated by Django 5.2 on 2025-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_details_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
